name: Build

on:
  push:
    branches:
    - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get_include
      run: |
        curl https://swupdate.openvpn.org/community/releases/openvpn-2.6.9.tar.gz | tar xz openvpn-2.6.9/include/openvpn-plugin.h
        cp openvpn-2.6.9/include/openvpn-plugin.h openvpn-plugin.h
    - name: build
      run: |
        make plugin
        sha256sum openvpn-plugin-auth-script.linux-amd64.tar.gz > sha256sum.txt    
    - uses: actions/upload-artifact@v4
      with:
        name: openvpn-plugin-auth-script
        path: |
          ./openvpn-plugin-auth-script.linux-amd64.tar.gz
          ./sha256sum.txt
        if-no-files-found: error
